 CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_number VARCHAR(100) NOT NULL,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_users_employee_number
    ON users (employee_number);

CREATE TABLE IF NOT EXISTS projects (
    project_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_name VARCHAR(255) NOT NULL,
    organization_name VARCHAR(255),
    description TEXT,
    version_id BIGINT DEFAULT 0,
    github_app_id VARCHAR(255),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS user_devices (
    user_device_id BIGINT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS histories (
    histories_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    version_id BIGINT NOT NULL,
    base_version_id BIGINT,
    user_github_id VARCHAR(255),
    encrypted_environment JSONB,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT fk_histories_project FOREIGN KEY (project_id) REFERENCES projects (project_id)
);

CREATE INDEX IF NOT EXISTS idx_histories_project_version
    ON histories (project_id, version_id DESC);

CREATE TABLE IF NOT EXISTS encrypted_keys (
    encrypted_key_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_device_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    encrypted_key TEXT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT fk_encrypted_keys_user_device FOREIGN KEY (user_device_id) REFERENCES user_devices (user_device_id),
    CONSTRAINT fk_encrypted_keys_project FOREIGN KEY (project_id) REFERENCES projects (project_id),
    CONSTRAINT uk_user_device_project UNIQUE (user_device_id, project_id)
);
