DROP TABLE IF EXISTS encrypted_keys;
DROP TABLE IF EXISTS histories;
DROP TABLE IF EXISTS user_devices;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS projects (
    project_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_name VARCHAR(255) NOT NULL,
    organization_name VARCHAR(255),
    description TEXT,
    version_id BIGINT DEFAULT 0,
    version BIGINT DEFAULT 0,
    github_app_id VARCHAR(255),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_github_id VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT uk_users_github_id UNIQUE (user_github_id)
);

CREATE TABLE IF NOT EXISTS user_devices (
    user_device_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    device_name VARCHAR(255) NOT NULL,
    public_key TEXT NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT fk_user_devices_user FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS histories (
    histories_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    version_id BIGINT NOT NULL,
    base_version_id BIGINT,
    user_github_id VARCHAR(255),
    encrypted_environment JSONB,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT fk_histories_project FOREIGN KEY (project_id) REFERENCES projects (project_id),
    CONSTRAINT uk_project_version UNIQUE (project_id, version_id)
);

CREATE INDEX IF NOT EXISTS idx_histories_project_version
    ON histories (project_id, version_id DESC);

CREATE TABLE IF NOT EXISTS encrypted_keys (
    encrypted_key_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_device_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    encrypted_key TEXT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT fk_encrypted_keys_user_device FOREIGN KEY (user_device_id) REFERENCES user_devices (user_device_id),
    CONSTRAINT fk_encrypted_keys_project FOREIGN KEY (project_id) REFERENCES projects (project_id),
    CONSTRAINT uk_user_device_project UNIQUE (user_device_id, project_id)
);
