name: Gradle Build

on:
  pull_request:
    branches: [ "main", "develop" ]
  push:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Core

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Load environment variables
        run: |
          echo "${{ secrets.ENV_FILE }}" >> $GITHUB_ENV

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Run Gradle build
        run: ./gradlew clean build -x test --no-daemon
